#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/forecast-by-vincent:latest@sha256:45ccb1b8618ae0efc3c0a11c70c27a86400b8991b223fc262fdf7ef5f354bfd4
    restart: on-failure:5
    environment:
      - PORT=3015
    ports:
      - "3015:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3015/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
