#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/forecast-by-vincent:latest@sha256:d4aa242b54ec938a061b91a0ce067df22baded2c9329ff8ed9f8a79b79bf122c
    restart: on-failure:5
    environment:
      - PORT=3015
    ports:
      - "3015:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3015/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
