#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/forecast-by-vincent:latest@sha256:0b52c4f2694743336aa851793ce3b9f7b40d5b6a0f597d5d833c47b9f61683a0
    restart: on-failure:5
    environment:
      - PORT=3015
    ports:
      - "3015:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3015/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
